### PR TITLE
Changes from MLA review stage

### PR DESCRIPTION
**Pull request by chriszarate**
Here are the changes from MLA's review stage. Apologies for not sending this over sooner; we'll make sure this happens quicker for the next round.

There are a number of white space and formatting changes here, which contributes to the size of the review. Let me know if these pose a problem and we can work on resubmitting.

### CODE REVIEW

**Comment by mkgold** [comment]
Thanks very much, Chris. We would like to merge most of these changes, but we have concerns about deleting the YAML blocks. Would it be possible for you to resubmit the merge request without those commits?

**Comment by chriszarate** [comment]
Hi Matt!

We didn't delete the YAML blocks. There is a commit message that says "remove leading yaml block," but that references a script we use to convert the Markdown to WordPress-ready HTML. There are also a number of white space and formatting changes to the YAML blocks, but browsing through the "Files changed" tab above should confirm that they are intact and fundamentally unchanged. Let me know if I'm missing something.

The changes you recently pushed created a merge conflict, so let me rebase and resubmit the PR so that you can merge it easily.

Chris

**Comment by chriszarate** [comment]
Ok! Ready to merge if you are.

**Comment by mkgold** [comment]
Aha! Thanks so much, Chris!!

**Pull request merged**
